version: '2'
services:
  nginx:
    container_name: gc.nginx
    image: nginx:latest
    ports:
      - "8082:80"
    depends_on:
      - php
    volumes_from:
      - php:ro
    restart: always
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    image: php:7-fpm
    container_name: gc.php
    volumes:
      - .:/var/www/html
    restart: always
    expose:
      - 9000
    entrypoint: /var/www/html/etc/entrypoint.sh

networks:
  default:
    external:
      name: jiraganttchart_default
